org: elioglima
app: aws-node-express-api-app
service: aws-node-express-api-app

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  stage: dev
  region: sa-east-1
  memorySize: 128

functions:
  api:
    handler: server.api
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
